project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Nelson Carvalho | Desenvolvedor"

  page-footer:
    left: "&copy; Copyright 2026, Nelson Carvalho"
    right: "Desenvolvido com [Quarto](https://quarto.org/)."

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: projects/index.qmd
        text: Trabalhos

      # - href: about.qmd
      #   text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



